import { Cloud, CloudFog, CloudLightning, CloudRain, CloudSnow, CloudSun, Home, Map, Newspaper, Search, Settings, Bookmark, Mic, X, Wind, Droplets, Gauge, Eye, Sunrise, Sunset, Radio } from 'lucide-react';
import { NavLink, Outlet } from 'react-router-dom';
import type { Condition, WeatherData, WeatherCurrent } from '@/types';
import { time, temp, wind } from '@/lib/format';
import { useSpeechSearch } from '@/hooks/useSpeechSearch';
import { useState } from 'react';
export function Icon({condition,size=28}:{condition:Condition;size?:number}){const C={clear:CloudSun,cloudy:Cloud,rain:CloudRain,storm:CloudLightning,snow:CloudSnow,fog:CloudFog,'partly-cloudy':CloudSun}[condition];return <C size={size}/>;}
const links=[['/','Home',Home],['/search','Search',Search],['/weather','Weather',CloudSun],['/weather/map','Weather Map',Map],['/news','News',Newspaper],['/saved','Saved',Bookmark]] as const;
export function Layout(){return <div className="shell"><aside><div className="logo"><span><Radio size={17}/></span>NEXUS</div><small>INTELLIGENCE OS</small><nav>{links.map(([to,label,C])=><NavLink to={to} end={to==='/' } key={to}><C size={18}/>{label}</NavLink>)}</nav><NavLink className="settings" to="/settings"><Settings size={18}/>Settings</NavLink><p className="online"><i/> Systems online</p></aside><header className="mobile-head"><div className="logo"><span><Radio size={15}/></span>NEXUS</div></header><main><div className="content"><Outlet/></div></main><nav className="bottom">{links.slice(0,5).map(([to,label,C])=><NavLink to={to} end={to==='/' } key={to}><C size={18}/><small>{label}</small></NavLink>)}</nav></div>}
export function SearchBox({onSearch,recent=[]}:{onSearch:(x:string)=>void;recent?:string[]}){const [value,setValue]=useState('');const {supported,listening,start}=useSpeechSearch(setValue);return <div className="search-wrap"><form className="searchbar" onSubmit={e=>{e.preventDefault();if(value.trim())onSearch(value.trim())}}><Search size={21}/><input value={value} onChange={e=>setValue(e.target.value)} placeholder="What do you want to know?" aria-label="Search"/>{value&&<button type="button" onClick={()=>setValue('')} aria-label="Clear"><X size={17}/></button>}{supported&&<button type="button" className={listening?'listen':''} onClick={start} aria-label="Voice search"><Mic size={18}/></button>}<button className="go" type="submit">Search</button></form>{!value&&recent.length>0&&<div className="chips">Recent: {recent.slice(0,3).map(x=><button key={x} onClick={()=>onSearch(x)}>{x}</button>)}</div>}</div>}
export function Current({data,tempUnit,windUnit}:{data:WeatherCurrent;tempUnit:'celsius'|'fahrenheit';windUnit:'kmh'|'mph'}){const m=[[Droplets,'Humidity',data.humidity+'%'],[Wind,'Wind',wind(data.wind,windUnit)],[Gauge,'Pressure',data.pressure+' hPa'],[Eye,'Visibility',data.visibility+' km']] as const;return <section className="card current"><div className="row"><div><small>LIVE CONDITIONS</small><h2>{data.location}</h2><p>{data.conditionLabel} · {time(data.updatedAt)}</p></div><Icon condition={data.condition} size={56}/></div><div className="temp"><b>{temp(data.temperature,tempUnit)}</b><span>Feels like {temp(data.feelsLike,tempUnit)}</span></div><div className="metrics">{m.map(([C,l,v])=><div key={l}><C size={16}/><span>{l}</span><b>{v}</b></div>)}</div><div className="sun"><span><Sunrise size={15}/> {data.sunrise}</span><span>Rain {data.rainProbability}%</span><span><Sunset size={15}/> {data.sunset}</span></div></section>}
export function Forecast({weather,tempUnit,windUnit}:{weather:WeatherData;tempUnit:'celsius'|'fahrenheit';windUnit:'kmh'|'mph'}){return <><section><div className="sect"><div><small>NEXT 24 HOURS</small><h3>Hourly forecast</h3></div></div><div className="hours">{weather.hourly.map(x=><div className="hour" key={x.time}><span>{time(x.time)}</span><Icon condition={x.condition} size={25}/><b>{temp(x.temperature,tempUnit)}</b><em>{x.rainProbability}% rain</em></div>)}</div></section><section><div className="sect"><div><small>EXTENDED OUTLOOK</small><h3>7-day forecast</h3></div></div><div className="days">{weather.daily.map(x=><div className="day" key={x.day}><b>{x.day}</b><Icon condition={x.condition}/><span>{x.conditionLabel}</span><em>{x.rainProbability}%</em><strong>{temp(x.high,tempUnit)} <i>{temp(x.low,tempUnit)}</i></strong><small>{wind(x.wind,windUnit)}</small></div>)}</div></section></>}
export function Ambient({condition='clear',reduced=false}:{condition?:Condition;reduced?:boolean}){return <div className={`ambient ${condition} ${reduced?'reduced':''}`} aria-hidden="true"><div className="stars"/><div className="clouds"/></div>}
